Exercise 4:

You are a lyric programmer and you are supposed to write a code that can output
lyrics to "99 bottles of beer"

Song:

99 bottles of beer on the wall, 99 bottles of beer.
Take one down and pass it around, 98 bottles of beer on the wall.

98 bottles of beer on the wall, 98 bottles of beer.
Take one down and pass it around, 97 bottles of beer on the wall.

....
....
....

1 bottle of beer on the wall, 1 bottle of beer.
Take one down and pass it around, no more bottles of beer on the wall.

No more bottles of beer on the wall, no more bottles of beer.
Go to the store and buy some more, 99 bottles of beer on the wall.

- alternatively -

No more bottles of beer on the wall, no more bottles of beer.
We've taken them down and passed them around; now we're drunk and passed out!

In [11]:
x=0
print('x is %%d', x)

x is %%d 0


In [21]:
n=100
count=1
for i in range(0,n):
    if i==99:
        print('No more bottles of beer on the wall, no more bottles of beer. Go to the store and buy some more, 99 bottles of beer on the wall.')
    elif i==98:
        print('%d bottles of beer on the wall, %d bottles of beer. Take one down and pass it around, no more bottles of beer on the wall.'%(99-i, 99-i))
    else:
        print('%d bottles of beer on the wall, %d bottles of beer. Take one down and pass it around, %d bottles of beer on the wall.'%(99-i, 99-i, 99-i-1))

99 bottles of beer on the wall, 99 bottles of beer. Take one down and pass it around, 98 bottles of beer on the wall.
98 bottles of beer on the wall, 98 bottles of beer. Take one down and pass it around, 97 bottles of beer on the wall.
97 bottles of beer on the wall, 97 bottles of beer. Take one down and pass it around, 96 bottles of beer on the wall.
96 bottles of beer on the wall, 96 bottles of beer. Take one down and pass it around, 95 bottles of beer on the wall.
95 bottles of beer on the wall, 95 bottles of beer. Take one down and pass it around, 94 bottles of beer on the wall.
94 bottles of beer on the wall, 94 bottles of beer. Take one down and pass it around, 93 bottles of beer on the wall.
93 bottles of beer on the wall, 93 bottles of beer. Take one down and pass it around, 92 bottles of beer on the wall.
92 bottles of beer on the wall, 92 bottles of beer. Take one down and pass it around, 91 bottles of beer on the wall.
91 bottles of beer on the wall, 91 bottles of beer. Take

# Week 40, TA session 1
## Python data types and structures, recap

Initially, we talked briefly about the degree of hands-on programming so far in the BS Data Science program, in order for me to get an idea of previous exposure to Python implementations.

Moving on, I asked wheher everybody had jupyter notebook/jupyter lab or another editor/IDE installed and ready to use. As this seemed to be the case, we moved on into a basic recap of Python data structures. If anybody are having issues setting up a working environment to program in, please let me know and I can see whether I can offer some help in getting it running, or direct to easy tutourials for the relevant operating system.

I further asked whether NLTK and packages were installed. To check it, simply run "import nltk" and it should not give an error if it is installed. If it isnt installed, go to your package manager (if you use one, such as anaconda), find it, and click install. 

(If you use a command line interface to manage your python installation and environments, you are probably aware of what to do to install packages (pip install..., conda install..., etc depending on chosen distribution).)

In [1]:
#we discussed whether everybody had jupyter installed, 
#as well as packages such as NLTK. To see whether NLTK is 
#installed, simply try importing it.
import nltk

## Python data types
Next, we covered some basic data types in Python.
### Integers

In [2]:
x = 2 #let x be the integer two (2).

In [3]:
type(x) #check what type x is, with the built in type() check.
        #It will tell you that it is an int.

int

In [4]:
print(str(x)+' : '+str(type(x))) #Now we are printing the value of 
                                #x, a colon, and its type 
                                #(<class 'int'>).
        
# note that you have to specify that the reply from the type() 
# statement and the value of x should be converted to string 
# in order for it to be concatenated with the string ' : ' in the
# print statement. 

2 : <class 'int'>


In [5]:
# remember that you have the common mathematical 
# operators +-*/ in Python. You also have power/exponentiation, as
# ** -- as in this example:
x = 2
print(x+3)
print(x-3)
print(x*3)
print(x/3)
print(x**3)

5
-1
6
0.6666666666666666
8


In [6]:
# if you ever see this syntax, it means x = x + 1:
x += 1
x

3

### Floats

In [7]:
y = 2.5 # let y be the decimal number 2.5 (a float)
type(y) # check what type it is

float

In [8]:
print(y,':',type(y)) # As with x further above. But not 
                     # concatenating (with +), rather simply 
                     # printing several expressions with a comma
                     # in between. Then there is no need to force
                     # everything into the string type (str()).
print('\n\nsome floats:') #note use of \n which means new line.
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

2.5 : <class 'float'>


some floats:
2.5 3.5 5.0 6.25


### Booleans
A bool can only hold either True, or False.

In [9]:
t = True 
f = False

In [10]:
type(t)

bool

In [11]:
t and f # booleans can be the result of a logical test. 
# here, we test whether both t and f are True. 
# They are not, thus, False is returned.

False

In [12]:
# We can perform other tests too
1 == 2

False

In [13]:
print(t and t)

True


### Strings

In [14]:
s = "hello" #assigning the string 'hello' to s  

In [15]:
s.capitalize() #makes first letter capital. 

'Hello'

In [16]:
s.upper() # makes all letters upper case

'HELLO'

In [17]:
s = '   world '

In [18]:
s.strip() #removes whitespace before and after

'world'

### Lists
remember that python indexing starts at 0  

In [19]:
names = ['0Zach', '1Jay'] 

In [20]:
names[0] #you can select an item with its index

'0Zach'

In [21]:
names[0] == '0Zach' #as for other structures, you can test whether an item meets a logical test, in this case an equals test

True

In [22]:
names.append('2Richard') # append adds what it is fed with to the end of the list on which it is used

In [23]:
names #we now have a list of three items

['0Zach', '1Jay', '2Richard']

In [24]:
len(names) #dont just count the number of items, let Python check the length with len()

3

In [25]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2]) #note how a list output looks vs only an item

[3, 1, 2] 2


In [26]:
xs[-1] #you can also index from the rear end of the list

2

In [27]:
xs[2] = 'text' #you can change an item in a list directly through use of its index. lists can hold various data types

In [28]:
xs

[3, 1, 'text']

In [29]:
type(xs) #the type is a list

list

In [30]:
type(xs[1]) #you can also check types for each item in a list

int

In [31]:
type(xs[2]) #and lists cam hold various types

str

In [32]:
xs.append('bar') #adding an item to the rear with append

In [33]:
xs

[3, 1, 'text', 'bar']

In [34]:
popitem = xs.pop() #removing an item from the list, assigning to the chosen variable, in this case popitem

In [35]:
popitem

'bar'

In [36]:
xs #'bar' was removed

[3, 1, 'text']

In [37]:
xs.append(10)

In [38]:
xs[2:] #slicing a list showing items from position two and to the end 

['text', 10]

In [39]:
xs[:int(len(xs)/2)] #slicing to get only about half of the list. note use of int to force it to an int - a list index cannot be float

[3, 1]

In [40]:
str(10) #regarding the use of types, you can treat numbers as string also. 10 --> '10'

'10'

In [41]:
animals = ['cat', 'dog', 'monkey'] #new example list




In [42]:
dict(enumerate(animals)) #enumerate adds numbered indices to a list. dict used to get output as a dictionary - a structure with key and value pairs.

{0: 'cat', 1: 'dog', 2: 'monkey'}

In [43]:
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# print syntax using % and variable names. shorter way of doing similar task as earlier in this notebook - namely concatenating numeric variables and string in a print statement

#1: cat
#2: dog
#3: monkey


### dictionary

In [44]:
d = {'cat': 'cute', 'dog': 'furry'}  # dictionary with some data

In [45]:
d['dog'] #selecting item by key

'furry'

In [46]:
d[10] = 150 #adding a key value pair

In [47]:
d

{'cat': 'cute', 'dog': 'furry', 10: 150}

In [48]:
print('cat' in d) #logical test of whether key 'cat' present in d 

True


In [49]:
d['fish'] = 'wet'     # new  key value pair in a dictionary

In [50]:
d

{'cat': 'cute', 'dog': 'furry', 10: 150, 'fish': 'wet'}

In [51]:
print(d.get('dog', 'N/A'))  #return value for key 'dog' - and if 'dog' not present, return 'N/A'. Try for yourselves with another key that is not present.

furry


In [52]:
d = {'person': {'legs':2, 'hands':2}, 'cat': {'legs':4,'hands':0}} #example of nested dictionaries. dict within a dict

In [53]:
d

{'person': {'legs': 2, 'hands': 2}, 'cat': {'legs': 4, 'hands': 0}}

In [54]:
d['person']['legs'] #selecting from a dict within a dict

2

### NumPy
NumPy is very useful for doing calculations on arrays, which are structured data in rows and columns. Think of a spreadsheet, if you like, but for NumPy without column names - only column numbers. NumPy arrays can quickly be transformed in shape (number of rows and number of columns) depending on the use case.

NumPy has great package documentation pages online.

In [55]:
import numpy as np # you typicall rename numpy to its common shorthandle np
a = np.array([[1,2,3],[4,5,6]]) #how an array is created

In [56]:
a #how it looks

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a[0,1] #how you select an item. note indexing on the vertical before horizontal.

2

In [58]:
type(a) #type numpy n-dimensional array

numpy.ndarray

In [59]:
a.shape #shape of the array, in the format vertical by horizontal

(2, 3)

In [60]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #re-creating a as a bigger array

In [61]:
a.shape

(3, 3)

In [62]:
a = np.zeros((3,3)) #re-creating a with only zeros

In [63]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) #recreating a even bigger

In [65]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a.shape

(3, 4)

In [67]:
b = a[:2, :3] #making a slice of a (think of it as a view), calling it b. 
b

array([[1, 2, 3],
       [5, 6, 7]])

In [68]:
b[0,1] = 5 # changing an item in the b (the view) means the same item in a is also changed! 
b

array([[1, 5, 3],
       [5, 6, 7]])

In [69]:
a #note position [0,1] which prior to our modification of b, held the integer 2. 

array([[ 1,  5,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b[0,2]= 10 #showing it one more time - a[0,2] was previously 3, but now - through a change in b - it is changed to 10

In [71]:
a

array([[ 1,  5, 10,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
a[0, 2]

10

In [73]:
# you can perform maths on the arrays - item on item. 
A = np.array([[1,2,3],[1,4,9],[1,8,17]])

B = np.array([[1,0,0],[0,1,0],[0,0,1]])

C = A-B

In [74]:
C

array([[ 0,  2,  3],
       [ 1,  3,  9],
       [ 1,  8, 16]])

To be continued with  practical challenges in NumPy slicing and basic Python data structure and data type operations on wednesday.