# Task 1 

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 

In [2]:
df = pd.read_csv(r'C:\Users\sebas\Desktop\heart.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
X = df.loc[:,df.columns!="target"]
type(X)

y = df["target"]
type(y)

pandas.core.series.Series

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
X_test_std

array([[ 1.69716475,  0.69617712, -0.92274852,  0.77251645, -1.36354075,
        -0.41803981,  0.90163913, -1.07375268,  1.40984195,  1.2900049 ,
        -2.27916533, -0.70710678,  1.14190596],
       [ 1.02496529,  0.69617712,  1.94013791,  2.23625729, -0.3703119 ,
        -0.41803981, -0.97936664,  0.22375805, -0.70929937, -0.38883987,
        -0.66169316, -0.70710678,  1.14190596],
       [ 0.46479907,  0.69617712,  1.94013791,  2.23625729,  0.7728383 ,
        -0.41803981, -0.97936664,  0.39675948, -0.70929937, -0.72460883,
        -0.66169316, -0.70710678,  1.14190596],
       [ 0.57683232,  0.69617712, -0.92274852, -0.39847623,  0.21063328,
        -0.41803981, -0.97936664, -0.38174696,  1.40984195,  1.45788938,
        -0.66169316,  0.26516504,  1.14190596],
       [ 0.8008988 ,  0.69617712,  0.98584243, -0.10572806, -0.29535123,
        -0.41803981,  0.90163913, -0.16549517, -0.70929937,  0.61846699,
        -0.66169316,  2.20970869,  1.14190596],
       [-0.7675666 ,  0.696177

In [8]:
from sklearn import svm
clf_svm_1 = svm.SVC(kernel='linear', C=0.1)
clf_svm_1.fit(X_train_std, y_train)


SVC(C=0.1, kernel='linear')

In [9]:
y_train_pred = clf_svm_1.predict(X_train_std)
y_test_pred = clf_svm_1.predict(X_test_std)

In [10]:
y_test_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int64)

# Model Accuracy

In [11]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [12]:
confusion_matrix(y_test, y_test_pred)

array([[19,  8],
       [ 4, 30]], dtype=int64)

In [13]:
accuracy_score(y_test,y_test_pred)

0.8032786885245902

In [14]:
clf_svm_1.n_support_

array([52, 54])

# Task 2, Grid Search. 
#### - With GridSearch we dont need to manually check every parameter which gives us the best accuracy

In [15]:
from sklearn.model_selection import GridSearchCV
params = {'C':(0.1,1,100)}
clf_svm_1=svm.SVC(kernel='linear')
svm_grid_lin=GridSearchCV(clf_svm_1, params, n_jobs=-1,
                         cv=10, verbose=1, scoring='accuracy')

In [16]:
svm_grid_lin.fit(X_train_std, y_train)
svm_grid_lin.best_params_
linsvm_clf = svm_grid_lin.best_estimator_
accuracy_score(y_test, linsvm_clf.predict(X_test_std))

Fitting 10 folds for each of 3 candidates, totalling 30 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 out of  30 | elapsed:    4.1s finished


0.8032786885245902

In [17]:
svm_grid_lin.best_params_

{'C': 0.1}

# Task 3 
### - We can see that the model we have went with gives us an accuracy of 80%, which is pretty good. We have done Grid Search, to find the best parameters within 0.1, 1 and 100. What we could do to find further improvements is to try more parameters. Considering the fact that our accuracy is at 80%, we can look to further improve but dont need. We could add more data or do better feature selection. 

# Task 4 
### - SVM classifier will fail  when implementing the wrong kernel function, for example introducing a linear kernel to data that is not linear sepearable. 
### - SVM classifier will fail if you do not put in the right key parameters, this can be mitigated with a GridSearch, which will showcase the best parameters out of a set of selected parameters. It can also be mitigated with MKL. 
### - SVM handles small to mid size datasets pretty well, but handling bigger datasets can be a issue. 
### In our case, SWM works good on the linear kernel which was randomly implemented, we do not have to big of a dataset to work with and we have also run GridSearch/Hyper tuning to find the best of the parameters. 

# Task 5
### - We can se that after running the Polynomial kernel and the RBF kernel we have significantly worse score than with a linear kernel. One of the key reasononings we have such a big difference in the accuracy scores could be a indication that we are dealing with a a dataset that has seperable datapoints. We achieved a score of 80 % compared to 55 and 57 % using the linear kernel. 
### - RBF is genereally outperforming the linear kernel, it may be overfitting or not correct cross validation within a grid search. 

# Cross Validation for poly and rbf 

In [48]:
from sklearn.model_selection import GridSearchCV
params = {'C':(0.1,1,10,25,50,100)}
clf_svm_p3=svm.SVC(kernel='poly')
svm_grid_lin=GridSearchCV(clf_svm_p3, params, n_jobs=-1,
                         cv=10, verbose=1, scoring='accuracy')

In [49]:
svm_grid_lin.fit(X_train_std, y_train)
svm_grid_lin.best_params_
linsvm_clf = svm_grid_lin.best_estimator_

Fitting 10 folds for each of 6 candidates, totalling 60 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  53 out of  60 | elapsed:    0.2s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  60 out of  60 | elapsed:    0.2s finished


In [50]:
svm_grid_lin.best_params_

{'C': 1}

In [51]:
from sklearn.model_selection import GridSearchCV
params = {'C':(0.1, 0.2, 1,10,25,50,100)}
clf_svm_r=svm.SVC(kernel='rbf')
svm_grid_lin=GridSearchCV(clf_svm_r, params, n_jobs=-1,
                         cv=10, verbose=1, scoring='accuracy')

In [52]:
svm_grid_lin.fit(X_train_std, y_train)
svm_grid_lin.best_params_
linsvm_clf = svm_grid_lin.best_estimator_

Fitting 10 folds for each of 7 candidates, totalling 70 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  63 out of  70 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=-1)]: Done  70 out of  70 | elapsed:    0.2s finished


In [53]:
svm_grid_lin.best_params_

{'C': 0.1}

# Polynomial kernel

In [37]:
clf_svm_p3 = svm.SVC(kernel='poly', degree= 2, C= 1)
clf_svm_p3.fit(X_train_std, y_train)

SVC(C=1, degree=2, kernel='poly')

In [38]:
y_train_pred = clf_svm_p3.predict(X_train_std)
y_test_pred = clf_svm_p3.predict(X_test_std)

In [39]:
accuracy_score(y_test,y_test_pred)

0.6885245901639344

In [40]:
clf_svm_p3.n_support_

array([92, 97])

# RBF kernel

In [54]:
clf_svm_r = svm.SVC(kernel='rbf', gamma=0.5, C=0.1)
clf_svm_r.fit(X_train_std, y_train)

SVC(C=0.1, gamma=0.5)

In [55]:
y_train_pred = clf_svm_r.predict(X_train_std)
y_test_pred = clf_svm_r.predict(X_test_std)

In [56]:
accuracy_score(y_test, y_test_pred)

0.5573770491803278

In [57]:
clf_svm_r.n_support_

array([111, 125])

# Sources:
##### https://www.kaggle.com/ronitf/heart-disease-uci
##### PGR210-1 21H Lecture 5 PDF. 